(* generated by dune *)

(** @canonical Dose_common.CudfAdd *)
module CudfAdd = Dose_common__CudfAdd

(** @canonical Dose_common.CudfDiff *)
module CudfDiff = Dose_common__CudfDiff

(** @canonical Dose_common.CudfSolver *)
module CudfSolver = Dose_common__CudfSolver

(** @canonical Dose_common.EdosSolver *)
module EdosSolver = Dose_common__EdosSolver

(** @canonical Dose_common.GitVersionInfo *)
module GitVersionInfo = Dose_common__GitVersionInfo

(** @canonical Dose_common.Shell_lexer *)
module Shell_lexer = Dose_common__Shell_lexer

(** @canonical Dose_common.Util *)
module Util = Dose_common__Util

(** @canonical Dose_common.VersionInfo *)
module VersionInfo = Dose_common__VersionInfo
