opam-version: "2.0"
lib: [
  "_build/install/default/lib/mccs/META"
  "_build/install/default/lib/mccs/dune-package"
  "_build/install/default/lib/mccs/glpk/internal/libmccs_glpk_stubs.a"
    {"glpk/internal/libmccs_glpk_stubs.a"}
  "_build/install/default/lib/mccs/glpk/internal/mccs_glpk.a"
    {"glpk/internal/mccs_glpk.a"}
  "_build/install/default/lib/mccs/glpk/internal/mccs_glpk.cma"
    {"glpk/internal/mccs_glpk.cma"}
  "_build/install/default/lib/mccs/glpk/internal/mccs_glpk.cmxa"
    {"glpk/internal/mccs_glpk.cmxa"}
  "_build/install/default/lib/mccs/glpk/internal/ocaml_mccs_glpk.cmi"
    {"glpk/internal/ocaml_mccs_glpk.cmi"}
  "_build/install/default/lib/mccs/glpk/internal/ocaml_mccs_glpk.cmt"
    {"glpk/internal/ocaml_mccs_glpk.cmt"}
  "_build/install/default/lib/mccs/glpk/internal/ocaml_mccs_glpk.cmx"
    {"glpk/internal/ocaml_mccs_glpk.cmx"}
  "_build/install/default/lib/mccs/glpk/internal/ocaml_mccs_glpk.ml"
    {"glpk/internal/ocaml_mccs_glpk.ml"}
  "_build/install/default/lib/mccs/libmccs_stubs.a"
  "_build/install/default/lib/mccs/mccs.a"
  "_build/install/default/lib/mccs/mccs.cma"
  "_build/install/default/lib/mccs/mccs.cmi"
  "_build/install/default/lib/mccs/mccs.cmt"
  "_build/install/default/lib/mccs/mccs.cmti"
  "_build/install/default/lib/mccs/mccs.cmx"
  "_build/install/default/lib/mccs/mccs.cmxa"
  "_build/install/default/lib/mccs/mccs.ml"
  "_build/install/default/lib/mccs/mccs.mli"
  "_build/install/default/lib/mccs/opam"
]
stublibs: [
  "_build/install/default/lib/stublibs/dllmccs_glpk_stubs.so"
  "_build/install/default/lib/stublibs/dllmccs_stubs.so"
]
doc: [
  "_build/install/default/doc/mccs/CHANGES.md"
  "_build/install/default/doc/mccs/README.md"
]
libexec: [
  "_build/install/default/lib/mccs/glpk/internal/mccs_glpk.cmxs"
    {"glpk/internal/mccs_glpk.cmxs"}
  "_build/install/default/lib/mccs/mccs.cmxs"
]
